vich_uploader:
    db_driver: orm

    mappings:
        recipe_images:
            uri_prefix: /uploads/images/recipes
            upload_destination: '%kernel.project_dir%/public/uploads/images/recipes'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer' #generate random number (name file)
            delete_on_remove: true
            delete_on_update: true

        user_images:
            uri_prefix: /uploads/images/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/images/avatar'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer' #generate random number (name file)
            delete_on_remove: true
            delete_on_update: true